#aws curd app
#version 1.0.0

service: aws-todolist-webapp
provider:
  name: aws
  runtime: nodejs14.x  
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-south-1
   iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:CreateBucket
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
        - s3:ListObjects

resources:
  Resources:
    S3OutputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}
        AccessControl: Private

functions:
  hello:
    handler: src/handler.hello        

    