#aws curd app
#version 1.0.0

service: aws-lambda-curd
provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:getObject
        - s3:putObject
        - s3:putBucketPolicy
        - states:startExecution
      Resource: "*"
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-south-1

functions:
  hello:
    handler: src/handler.hello
