#aws curd app
#version 1.0.0

service: aws-lambda-curd
provider:
  name: aws
  runtime: nodejs14.x  
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-south-1
  Action: s3:*
    Effect: Allow
      Resource:
        arn:aws:s3:::todo
        arn:aws:s3:::todo/*

functions:
  hello:
    handler: src/handler.hello
